export const USER_SIGNIN_REQUEST='USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS='USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_ERROR='USER_SIGNIN_ERROR'

export const USER_SIGNUP_REQUEST='USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS='USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_ERROR='USER_SIGNUP_ERROR'

